# Generated by Django 4.1 on 2022-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.IntegerField(max_length=999, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=99)),
                ('reference', models.CharField(max_length=999)),
                ('description', models.CharField(max_length=9999)),
                ('extra', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.IntegerField(max_length=999, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('province', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('city', models.CharField(max_length=99)),
                ('sector', models.CharField(max_length=99)),
                ('reference', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='quarantine',
            fields=[
                ('id', models.IntegerField(max_length=999, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('province', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('beds', models.IntegerField(max_length=999)),
                ('reference', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='sqliteseq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('seq', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='summery',
            fields=[
                ('id', models.IntegerField(max_length=999, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('total_test', models.CharField(max_length=9999)),
                ('total_cases', models.CharField(max_length=9999)),
                ('total_recovered', models.CharField(max_length=9999)),
                ('total_deaths', models.CharField(max_length=9999)),
                ('total_critical', models.CharField(max_length=9999)),
                ('last_test', models.CharField(max_length=9999)),
                ('last_cases', models.CharField(max_length=9999)),
                ('last_recovered', models.CharField(max_length=9999)),
                ('last_deaths', models.CharField(max_length=9999)),
                ('last_critical', models.CharField(max_length=9999)),
                ('reference', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.IntegerField(max_length=999, primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=999)),
                ('total_fully', models.CharField(max_length=999)),
                ('total_partially', models.CharField(max_length=999)),
                ('total_doses', models.CharField(max_length=999)),
                ('last_fully', models.CharField(max_length=999)),
                ('last_partially', models.CharField(max_length=999)),
                ('last_doses', models.CharField(max_length=999)),
                ('reference', models.CharField(max_length=999)),
            ],
        ),
    ]
